######################################################################
# Automatically generated by qmake (2.01a) mer. 21. janv. 23:30:41 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += boutonDemineur.h Fenetre.h jeu.h Options.h
SOURCES += boutonDemineur.cpp Fenetre.cpp jeu.cpp main.cpp Options.cpp
